sonar.projectKey=meleksabit_simple-go-service
sonar.organization=meleksabit
sonar.host.url=https://sonarcloud.io
sonar.login=${env.SONAR_TOKEN}

sonar.language=go
sonar.sources=cmd/simple-go-service
sonar.tests=cmd/simple-go-service
sonar.go.coverage.reportPaths=coverage.out
